name: Publish Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: pnpm install
      - run: pnpm build
      
      # Pre-download MongoDB binary
      - name: Cache MongoDB Memory Server binaries
        uses: actions/cache@v4
        with:
          path: ~/.cache/mongodb-memory-server
          key: ${{ runner.os }}-mongodb-memory-server
          restore-keys: |
            ${{ runner.os }}-mongodb-memory-server
      
      # Set environment variable to skip binary download if cached
      - name: Set MongoDB Memory Server Variables
        run: |
          echo "MONGOMS_SYSTEM_BINARY=$HOME/.cache/mongodb-memory-server/mongodb-binaries" >> $GITHUB_ENV
          echo "MONGOMS_DOWNLOAD_URL=https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu2204-6.0.11.tgz" >> $GITHUB_ENV
      
      - name: Run tests
        run: NODE_ENV=test pnpm test
        
      - name: Publish to NPM
        run: NODE_ENV=production pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      
      - uses: actions/setup-node@v3
        with:
          registry-url: 'https://npm.pkg.github.com'
      - name: Publish to GitHub Packages
        run: NODE_ENV=production pnpm publish --no-git-checks --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
