name: Publish Package

on:
  release:
    types: [created] # Se ejecuta cuando se crea un release en GitHub
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Tag of the release to publish (e.g., v1.0.0)'
        required: true
        type: string

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      # Paso 1: Checkout del código
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name || github.event.inputs.release_tag }}
      
      # Paso 2: Configurar Node.js con npm
      - uses: actions/setup-node@v4
        with:
          node-version: '21'
          registry-url: 'https://registry.npmjs.org'
          auth-token: ${{ secrets.NPM_TOKEN }}

      # Paso 3: Instalar PNPM
      - uses: pnpm/action-setup@v4
        with:
          version: 9

      # Paso 4: Instalar dependencias
      - run: pnpm install
    
      # Paso 6: Publicar el paquete en npm
      - name: Publish to NPM
        run: pnpm publish --access public --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
         

  publish-github:
    needs: publish-npm
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      # Paso 1: Checkout del código
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name || github.event.inputs.release_tag }}
      
      # Paso 2: Configurar Node.js para GitHub Packages
      - uses: actions/setup-node@v4
        with:
          node-version: '21'
          registry-url: 'https://npm.pkg.github.com'
          auth-token: ${{ secrets.GITHUB_TOKEN }}

      # Paso 3: Instalar PNPM
      - uses: pnpm/action-setup@v4
        with:
          version: 9

      # Paso 4: Instalar dependencias
      - run: pnpm install
     
      # Paso 6: Publicar el paquete en GitHub Packages
      - name: Publish to GitHub Packages
        run: pnpm publish --access public --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
