name: Publish Package

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Tag of the release to publish (e.g., v1.0.0)'
        required: true
        type: string

permissions:
  contents: read
  id-token: write
  packages: write

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name || github.event.inputs.release_tag }}

      - uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: '21'
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      # Create a clean .npmrc for npm publishing
      - name: Create .npmrc for NPM publishing
        run: |
          echo "engine-strict=true" > .npmrc
          echo "auto-install-peers=true" >> .npmrc
          echo "shamefully-hoist=true" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=\${NODE_AUTH_TOKEN}" >> .npmrc
          echo "registry=https://registry.npmjs.org/" >> .npmrc
          
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
    
      - name: Publish to NPM
        run: |
          echo "Publishing to NPM..."
          pnpm config set registry https://registry.npmjs.org/
          pnpm publish --access public --provenance --no-git-checks --registry https://registry.npmjs.org/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_REGISTRY: "https://registry.npmjs.org"

  publish-github:
    needs: publish-npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name || github.event.inputs.release_tag }}

      - uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: '21'
          cache: 'pnpm'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@imigueldiaz'

      # Create a clean .npmrc for GitHub publishing
      - name: Create .npmrc for GitHub publishing
        run: |
          echo "engine-strict=true" > .npmrc
          echo "auto-install-peers=true" >> .npmrc
          echo "shamefully-hoist=true" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=\${NODE_AUTH_TOKEN}" >> .npmrc
          echo "@imigueldiaz:registry=https://npm.pkg.github.com" >> .npmrc

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
     
      - name: Publish to GitHub Packages
        run: |
          echo "Publishing to GitHub Packages..."
          pnpm config set registry https://npm.pkg.github.com/
          pnpm publish --access public --provenance --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}