name: Publish Package

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Tag of the release to publish (e.g., v1.0.0)'
        required: true
        type: string

permissions:
  contents: read
  id-token: write
  packages: write

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name || github.event.inputs.release_tag }}

      - uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: '21'
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      # Create a complete .npmrc for npm publishing
      - name: Create .npmrc for NPM publishing
        run: |
          cat > .npmrc << EOF
          engine-strict=true
          auto-install-peers=true
          shamefully-hoist=true
          
          //registry.npmjs.org/:_authToken=\${NODE_AUTH_TOKEN}
          registry=https://registry.npmjs.org/
          EOF

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
    
      - name: Publish to NPM
        run: pnpm publish --access public --provenance --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-github:
    needs: publish-npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name || github.event.inputs.release_tag }}

      - uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: '21'
          cache: 'pnpm'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@imigueldiaz'

      # Create a complete .npmrc for GitHub publishing
      - name: Create .npmrc for GitHub publishing
        run: |
          cat > .npmrc << EOF
          engine-strict=true
          auto-install-peers=true
          shamefully-hoist=true
          
          //npm.pkg.github.com/:_authToken=\${NODE_AUTH_TOKEN}
          @imigueldiaz:registry=https://npm.pkg.github.com
          EOF

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
     
      - name: Publish to GitHub Packages
        run: pnpm publish --access public --provenance --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}